language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "OracleJDK 8"
      jdk: oraclejdk8
      script: mvn -q clean verify -B -DskipNpm -DskipDocker
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request
      script: bash .travis.deploy.artifacts.sh
deploy:
  condition: env(GITHUB_TOKEN) IS present
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  repo: vertx-ci/vertx-docs-snapshot
  target-branch: master
  local-dir: ./stack-docs/target/html
  on:
    branch: master
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
